version: '3'

services:
  creative-build-server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
      - 80:8123
    environment:
      - EULA=TRUE
      - TYPE=PURPUR # use PURPUR for optimal performance with plugins
      - SERVER_NAME="Creative with Worldedit"
      - GENERATOR=FLAT
      - DIFFICULTY=peaceful
      - OPS=${OPS}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - MODE=creative # set to creative to allow for building
      - GENERATE_STRUCTURES=false
      - MOTD=Build the Elmshorn Campus with Worldedit in Creative Mode
      # Install Worldedit and Dynmap
      - MODS=https://dev.bukkit.org/projects/worldedit/files/latest
      # Install LuckPerms to allow for users to use Worldedit
      - SPIGET_RESOURCES=28140
    volumes:
      - creative-data:/data/
  survival-server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25566:25565
      - 81:8123
    environment:
      - EULA=TRUE
      - TYPE=PURPUR # use PURPUR for optimal performance with plugins
      - SERVER_NAME="Survival"
      - OPS=${OPS}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - MODE=survival # set to creative to allow for building
      - FORCE_GAMEMODE=true
      - GENERATE_STRUCTURES=true
      - MOTD=Survival Server
      # Install Worldedit to fix issues if necessary
      - MODS=https://dev.bukkit.org/projects/worldedit/files/latest
      # Install LuckPerms to allow for admins or mods to use Worldedit
      - SPIGET_RESOURCES=28140
    volumes:
      - survival-data:/data/
  
  last-man-standing-server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25567:25565
      - 82:8123
    environment:
      - EULA=TRUE
      - TYPE=PURPUR # use PURPUR for optimal performance with plugins
      - SERVER_NAME="Last Man Standing"
      - OPS=${OPS}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - MODE=survival # set to creative to allow for building
      - GENERATE_STRUCTURES=false # To not give Players an unfair Advantage
      - MOTD=Last Man Standing
      - SPIGET_RESOURCES=28140

    volumes:
      - last-man-standing-data:/data/

volumes:
  creative-data:
  survival-data:
  last-man-standing-data: