version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - 'etc-pihole:/etc/pihole'
      - 'etc-dnsmasq:/etc/dnsmasq.d'

volumes:
  etc-pihole:
  etc-dnsmasq: